import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


const Sports: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Editstars</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {/* Header */}
      <header className={styles.header}>
        <h1 className={styles.headerTitle}>Sports</h1>
      </header>
      <div className={styles.connectButton}>
        <ConnectButton />
      </div>
      <main className={styles.main}>
        <div className={styles.sectionContentCenter}>
          {/* Content for the centered section goes here */}

          <div className={`${styles.cardRowFive}`}>
            {/* Use the new cardFive class for a 5-card row */}
            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Arda Turan throwing shoe</h2>
              
            </a>

            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Cristiano Ronaldo grinning</h2>
            </a>

            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Messi looking at the scoreboard</h2>
            </a>

            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Emeghara taca atıyo topu</h2>
            </a>

            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Icardi Recep İvedik transition</h2>
            </a>
            <a className={styles.cardFive} href="sports">
              <img className={`${styles.contentImage}`} src="https://www.si.com/.image/t_share/MTY4MTkyNDA1NjQzMzM5NjQ5/arda-turan-throws-shoe-referee-video.png" alt="React Image" />
              <h2>Hamınada mamınada</h2>
            </a>
            {/* Add more cards as needed */}
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by YOURRAK
        </a>
      </footer>
    </div>
  );
};

export default Sports;