import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';

const Header:NextPage =  () => {
  return (
    <div>
        <Head>
        <title>Editstars</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {/* Header */}
      <header className={styles.header}>
        <div className={styles.logoContainer}>
          <img
            className={styles.logo}
            src="https://cdn.freebiesupply.com/logos/large/2x/silver-star-logo-png-transparent.png"
            alt="Your Logo"
          />
        </div>
        <h1 className={styles.headerTitle}>EDIT STARS</h1>
        <div className={styles.connectButton}>
          <ConnectButton />
        </div>
      </header>

    </div>
  )
}

export default Header;