import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import star from '../starlogo.png';

const Header:NextPage =  () => {
  return (
    <div>
        <Head>
        <title>Editstars</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {/* Header */}
      <header className={styles.header}>
      <div className={styles.logo}>
        <a href="/">
          <Image src={star} alt="Star Logo" width={100} height={100} />
          </a>
        </div>
        <h1 className={styles.headerTitle}>EDIT STARS</h1>
        <div className={styles.connectButton}>
          <ConnectButton />
        </div>
      </header>

    </div>
  )
}

export default Header;